version: 2

jobs:
  build:
    docker:
      - image: circleci/node:8.9.4
    steps:
      - checkout
      - run: npm install
  deploy:
    machine: true
    steps:
      - checkout
      - run: docker info
      - run: docker build --rm=false -t storager/docker:test .
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
